# Generated by Django 5.1.2 on 2024-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
