# Generated by Django 5.1.3 on 2024-11-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_alter_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
