# Generated by Django 5.1.2 on 2024-10-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('date_payement', models.DateTimeField()),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('payement_method', models.CharField(choices=[('PAYPAL', 'paypal'), ('CARTE_CREDIT', 'carte_credit'), ('ORANGE_MONEY', 'orange_money'), ('MTN_MONEY', 'mtn_money')])),
                ('status_payement', models.CharField(choices=[('REUSSIR', 'reussir'), ('ECHOUE', 'echoue')])),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservations.reservation')),
            ],
        ),
    ]
